services:
  # The MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Django Web Application Service
  server:
    build: .
    container_name: django_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SQL_HOST=db
      - SQL_PORT=3306
      - OLLAMA_HOST=ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_web
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
      - "4173:4173"
    depends_on:
      - server

volumes:
  mysql_data:
