# Generated by Django 5.2.6 on 2025-10-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='power_ups_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='used_scout_plane',
            field=models.BooleanField(default=False),
        ),
    ]
