# Generated by Django 5.2.6 on 2025-10-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_game_power_ups_enabled_player_used_scout_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='emp_active_on_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_effect', to='backend.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='used_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='used_torpedo',
            field=models.BooleanField(default=False),
        ),
    ]
