# Generated by Django 5.2.6 on 2025-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game_emp_active_on_player_player_used_emp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
