# Generated by Django 5.2.6 on 2025-09-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='is_sunk',
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='misses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='hits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='placing_ships', max_length=20),
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('is_hit', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_fired', to='game.player')),
            ],
        ),
    ]
