name: Deploy to EC2

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, PROD]
    steps:
      - name: Checkout code
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Remove old files
        run: |
          sudo rm -rf /home/ec2-user/battleshipgame
          cd /home/ec2-user
          mkdir battleshipgame

      - name: Copy code to ec2
        run: |
          cp -a * /home/ec2-user/battleshipgame

      - name: Make frontend
        run: |
          cd /home/ec2-user/battleshipgame/frontend
          npm i 
          npm run build
          sudo mv dist/* /var/www/html/

      - name: Execute code
        run: |
          cd /home/ec2-user/battleshipgame
          sudo docker-compose up -d --build --force-recreate

